# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NETIntfc_fish_disfull.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 1528, 960))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget QTabBar::tab{\n"
"    width:150;\n"
"    height:50;\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 24pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background: rgb(70, 130, 180);\n"
"    border: 2px;\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    margin-left: 40px;\n"
"    margin-top: 5px;\n"
"    margin-right: 20px;\n"
"    margin-bottom: 40px;\n"
"}\n"
"\n"
"/*QTabBar::tab:hover, QTabBar::tab:selected{background:white;\n"
"    border: 2px solid rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    color:rgb(99, 145, 182);}\n"
"*/\n"
"QTabBar::tab:hover{background:white;\n"
"    /*border: 2px solid rgb(99, 145, 182);*/\n"
"    border-color: rgb(99, 145, 182);\n"
"    color:rgb(99, 145, 182);}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background:white;\n"
"    /*border: 2px solid rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);*/\n"
"    color:rgb(99, 145, 182);\n"
"}\n"
"/* make non-selected tabs look smaller */\n"
"/*QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}*/\n"
"QTabWidget {\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.monitor = QtWidgets.QWidget()
        self.monitor.setObjectName("monitor")
        self.media_display = QtWidgets.QLabel(self.monitor)
        self.media_display.setGeometry(QtCore.QRect(0, 0, 1528, 860))
        self.media_display.setMaximumSize(QtCore.QSize(1528, 16777215))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.media_display.setFont(font)
        self.media_display.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.media_display.setStyleSheet("background-color: rgb(138, 138, 138);\n"
"border-color: rgb(2, 2, 2);\n"
"font:26pt \"STZhongsong\";")
        self.media_display.setAlignment(QtCore.Qt.AlignCenter)
        self.media_display.setObjectName("media_display")
        self.txt_tab = QtWidgets.QLabel(self.monitor)
        self.txt_tab.setGeometry(QtCore.QRect(10, 10, 240, 70))
        self.txt_tab.setStyleSheet("font: bold 40pt \"黑体\";\n"
"color: rgb(0, 0, 255);\n"
"background:transparent;\n"
"background:rgba(192,192,192, 40%);\n"
"border-color: rgba(192,192,192, 40%);\n"
"border-radius: 12px;\n"
"border: 2px;")
        self.txt_tab.setText("")
        self.txt_tab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_tab.setObjectName("txt_tab")
        self.tabWidget.addTab(self.monitor, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.build_display = QtWidgets.QLabel(self.tab_3)
        self.build_display.setGeometry(QtCore.QRect(60, 50, 455, 641))
        self.build_display.setMaximumSize(QtCore.QSize(1520, 16777215))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.build_display.setFont(font)
        self.build_display.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.build_display.setStyleSheet("background-color: rgb(138, 138, 138);\n"
"border-color: rgb(2, 2, 2);\n"
"font: 26pt \"STZhongsong\";")
        self.build_display.setAlignment(QtCore.Qt.AlignCenter)
        self.build_display.setObjectName("build_display")
        self.line_12 = QtWidgets.QFrame(self.tab_3)
        self.line_12.setGeometry(QtCore.QRect(20, 20, 1488, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab_3)
        self.line_13.setGeometry(QtCore.QRect(20, 20, 3, 815))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.tab_3)
        self.line_14.setGeometry(QtCore.QRect(20, 835, 1488, 3))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.tab_3)
        self.line_15.setGeometry(QtCore.QRect(1508, 20, 3, 815))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.frame_25 = QtWidgets.QFrame(self.tab_3)
        self.frame_25.setGeometry(QtCore.QRect(190, 700, 691, 111))
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(20)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.build_begin = QtWidgets.QPushButton(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.build_begin.sizePolicy().hasHeightForWidth())
        self.build_begin.setSizePolicy(sizePolicy)
        self.build_begin.setMinimumSize(QtCore.QSize(300, 75))
        self.build_begin.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.build_begin.setFont(font)
        self.build_begin.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.build_begin.setObjectName("build_begin")
        self.gridLayout_8.addWidget(self.build_begin, 0, 0, 1, 1)
        self.build_stop = QtWidgets.QPushButton(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.build_stop.sizePolicy().hasHeightForWidth())
        self.build_stop.setSizePolicy(sizePolicy)
        self.build_stop.setMinimumSize(QtCore.QSize(300, 75))
        self.build_stop.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.build_stop.setFont(font)
        self.build_stop.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.build_stop.setObjectName("build_stop")
        self.gridLayout_8.addWidget(self.build_stop, 0, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.tab_3)
        self.line_16.setGeometry(QtCore.QRect(1050, 40, 3, 775))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(1080, 40, 400, 771))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_21.setStyleSheet("font: bold 22pt \"黑体\";")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem1)
        self.manual_4 = QtWidgets.QLabel(self.groupBox_5)
        self.manual_4.setMaximumSize(QtCore.QSize(370, 1000))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.manual_4.setFont(font)
        self.manual_4.setStyleSheet("font: 20pt \"宋体\";")
        self.manual_4.setTextFormat(QtCore.Qt.AutoText)
        self.manual_4.setScaledContents(False)
        self.manual_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.manual_4.setWordWrap(True)
        self.manual_4.setIndent(-1)
        self.manual_4.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.manual_4.setObjectName("manual_4")
        self.verticalLayout_9.addWidget(self.manual_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 360, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem2)
        self.build_result = QtWidgets.QLabel(self.tab_3)
        self.build_result.setGeometry(QtCore.QRect(555, 50, 455, 640))
        self.build_result.setMaximumSize(QtCore.QSize(1520, 16777215))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.build_result.setFont(font)
        self.build_result.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.build_result.setStyleSheet("background-color: rgb(138, 138, 138);\n"
"border-color: rgb(2, 2, 2);\n"
"font: 26pt \"STZhongsong\";")
        self.build_result.setAlignment(QtCore.Qt.AlignCenter)
        self.build_result.setObjectName("build_result")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.num_dis = QtWidgets.QTableWidget(self.tab)
        self.num_dis.setGeometry(QtCore.QRect(45, 45, 743, 770))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.num_dis.setFont(font)
        self.num_dis.setObjectName("num_dis")
        self.num_dis.setColumnCount(3)
        self.num_dis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        item.setFont(font)
        self.num_dis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        item.setFont(font)
        self.num_dis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        item.setFont(font)
        self.num_dis.setHorizontalHeaderItem(2, item)
        self.num_dis.horizontalHeader().setDefaultSectionSize(247)
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(20, 20, 1488, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(20, 835, 1488, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(20, 20, 3, 815))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setGeometry(QtCore.QRect(1508, 20, 3, 815))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(810, 40, 3, 775))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(830, 50, 651, 751))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem3)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_19.setStyleSheet("font: bold 22pt \"STZhongsong\";")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem4)
        self.manual_3 = QtWidgets.QLabel(self.groupBox_4)
        self.manual_3.setMaximumSize(QtCore.QSize(600, 1000))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.manual_3.setFont(font)
        self.manual_3.setStyleSheet("font: 11pt \"宋体\";")
        self.manual_3.setTextFormat(QtCore.Qt.AutoText)
        self.manual_3.setScaledContents(False)
        self.manual_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.manual_3.setWordWrap(True)
        self.manual_3.setIndent(-1)
        self.manual_3.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.manual_3.setObjectName("manual_3")
        self.verticalLayout_8.addWidget(self.manual_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 380, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab, "")
        self.system_cfg = QtWidgets.QWidget()
        self.system_cfg.setObjectName("system_cfg")
        self.line_2 = QtWidgets.QFrame(self.system_cfg)
        self.line_2.setGeometry(QtCore.QRect(20, 20, 3, 815))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.system_cfg)
        self.line_3.setGeometry(QtCore.QRect(20, 20, 1488, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.system_cfg)
        self.line_4.setGeometry(QtCore.QRect(20, 835, 1488, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.system_cfg)
        self.line_5.setGeometry(QtCore.QRect(1508, 20, 3, 815))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget = QtWidgets.QWidget(self.system_cfg)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 751, 761))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(148, 40))
        self.label_18.setMaximumSize(QtCore.QSize(148, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.video_format_group = QtWidgets.QFrame(self.layoutWidget)
        self.video_format_group.setObjectName("video_format_group")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.video_format_group)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.video_format_mp4 = QtWidgets.QRadioButton(self.video_format_group)
        self.video_format_mp4.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_format_mp4.setFont(font)
        self.video_format_mp4.setStyleSheet("font: 16pt \"黑体\";")
        self.video_format_mp4.setChecked(True)
        self.video_format_mp4.setObjectName("video_format_mp4")
        self.horizontalLayout_19.addWidget(self.video_format_mp4)
        self.video_format_mkv = QtWidgets.QRadioButton(self.video_format_group)
        self.video_format_mkv.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_format_mkv.setFont(font)
        self.video_format_mkv.setStyleSheet("font: 16pt \"黑体\";")
        self.video_format_mkv.setObjectName("video_format_mkv")
        self.horizontalLayout_19.addWidget(self.video_format_mkv)
        self.video_format_avi = QtWidgets.QRadioButton(self.video_format_group)
        self.video_format_avi.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_format_avi.setFont(font)
        self.video_format_avi.setStyleSheet("font: 16pt \"黑体\";")
        self.video_format_avi.setObjectName("video_format_avi")
        self.horizontalLayout_19.addWidget(self.video_format_avi)
        self.gridLayout_3.addWidget(self.video_format_group, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 40))
        self.label_5.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setMinimumSize(QtCore.QSize(148, 40))
        self.label_32.setMaximumSize(QtCore.QSize(148, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(120, 40))
        self.label_6.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.curr_table_dir = QtWidgets.QLabel(self.layoutWidget)
        self.curr_table_dir.setMinimumSize(QtCore.QSize(410, 40))
        self.curr_table_dir.setMaximumSize(QtCore.QSize(410, 80))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curr_table_dir.setFont(font)
        self.curr_table_dir.setStyleSheet("border-style:solid;\n"
"border-color:rgb(125,125,125);\n"
"border-width:1px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"华文细黑\";")
        self.curr_table_dir.setObjectName("curr_table_dir")
        self.horizontalLayout_28.addWidget(self.curr_table_dir)
        self.change_table_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.change_table_dir.setMinimumSize(QtCore.QSize(65, 40))
        self.change_table_dir.setMaximumSize(QtCore.QSize(65, 40))
        self.change_table_dir.setStyleSheet("QPushButton{\n"
"    font-family: \"黑体\";\n"
"    font-size: 16pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.change_table_dir.setObjectName("change_table_dir")
        self.horizontalLayout_28.addWidget(self.change_table_dir)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 6, 1, 1, 1)
        self.cpu_tempeture_label = QtWidgets.QLabel(self.layoutWidget)
        self.cpu_tempeture_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_tempeture_label.setMaximumSize(QtCore.QSize(50000, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cpu_tempeture_label.setFont(font)
        self.cpu_tempeture_label.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.cpu_tempeture_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_tempeture_label.setObjectName("cpu_tempeture_label")
        self.gridLayout_3.addWidget(self.cpu_tempeture_label, 3, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.curr_video_dir = QtWidgets.QLabel(self.layoutWidget)
        self.curr_video_dir.setMinimumSize(QtCore.QSize(410, 40))
        self.curr_video_dir.setMaximumSize(QtCore.QSize(410, 80))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curr_video_dir.setFont(font)
        self.curr_video_dir.setStyleSheet("border-style:solid;\n"
"border-color:rgb(125,125,125);\n"
"border-width:1px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"华文细黑\";")
        self.curr_video_dir.setObjectName("curr_video_dir")
        self.horizontalLayout_18.addWidget(self.curr_video_dir)
        self.change_video_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.change_video_dir.setMinimumSize(QtCore.QSize(65, 40))
        self.change_video_dir.setMaximumSize(QtCore.QSize(65, 40))
        self.change_video_dir.setStyleSheet("QPushButton{\n"
"    font-family: \"黑体\";\n"
"    font-size: 16pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.change_video_dir.setObjectName("change_video_dir")
        self.horizontalLayout_18.addWidget(self.change_video_dir)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 4, 1, 1, 1)
        self.ram_usage_label = QtWidgets.QLabel(self.layoutWidget)
        self.ram_usage_label.setMinimumSize(QtCore.QSize(120, 40))
        self.ram_usage_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ram_usage_label.setFont(font)
        self.ram_usage_label.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.ram_usage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ram_usage_label.setObjectName("ram_usage_label")
        self.gridLayout_3.addWidget(self.ram_usage_label, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(120, 40))
        self.label_16.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font: 16pt \"黑体\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(120, 40))
        self.label_7.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(148, 40))
        self.label_13.setMaximumSize(QtCore.QSize(148, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.cpu_usage_label = QtWidgets.QLabel(self.layoutWidget)
        self.cpu_usage_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_usage_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cpu_usage_label.setFont(font)
        self.cpu_usage_label.setStyleSheet("QLabel {\n"
"    font: 16pt \"黑体\";\n"
"}")
        self.cpu_usage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_usage_label.setObjectName("cpu_usage_label")
        self.gridLayout_3.addWidget(self.cpu_usage_label, 2, 1, 1, 1)
        self.det_en_group = QtWidgets.QFrame(self.layoutWidget)
        self.det_en_group.setMinimumSize(QtCore.QSize(120, 40))
        self.det_en_group.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.det_en_group.setFont(font)
        self.det_en_group.setObjectName("det_en_group")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.det_en_group)
        self.horizontalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.det_state_on = QtWidgets.QRadioButton(self.det_en_group)
        self.det_state_on.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.det_state_on.setFont(font)
        self.det_state_on.setStyleSheet("font: 16pt \"黑体\";")
        self.det_state_on.setChecked(True)
        self.det_state_on.setObjectName("det_state_on")
        self.horizontalLayout_15.addWidget(self.det_state_on)
        self.det_state_off = QtWidgets.QRadioButton(self.det_en_group)
        self.det_state_off.setMaximumSize(QtCore.QSize(80, 16777215))
        self.det_state_off.setStyleSheet("font: 16pt \"黑体\";")
        self.det_state_off.setObjectName("det_state_off")
        self.horizontalLayout_15.addWidget(self.det_state_off)
        self.gridLayout_3.addWidget(self.det_en_group, 0, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.system_cfg)
        self.line_6.setGeometry(QtCore.QRect(800, 40, 3, 775))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_8 = QtWidgets.QLabel(self.system_cfg)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 741, 31))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.system_cfg)
        self.groupBox_3.setGeometry(QtCore.QRect(835, 40, 651, 771))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setStyleSheet("font: bold 22pt \"STZhongsong\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem7)
        self.manual_2 = QtWidgets.QLabel(self.groupBox_3)
        self.manual_2.setMaximumSize(QtCore.QSize(624, 1000))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.manual_2.setFont(font)
        self.manual_2.setStyleSheet("font: 14pt \"宋体\";")
        self.manual_2.setTextFormat(QtCore.Qt.AutoText)
        self.manual_2.setScaledContents(False)
        self.manual_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.manual_2.setWordWrap(True)
        self.manual_2.setIndent(-1)
        self.manual_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.manual_2.setObjectName("manual_2")
        self.verticalLayout_7.addWidget(self.manual_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem8)
        self.tabWidget.addTab(self.system_cfg, "")
        self.status_bg = QtWidgets.QFrame(self.centralwidget)
        self.status_bg.setGeometry(QtCore.QRect(0, 90, 1920, 60))
        self.status_bg.setStyleSheet("QFrame {\n"
"    background-color: rgb(70, 130, 180);\n"
"    border: 2px;\n"
"    border-color: rgb(0, 99, 180);\n"
"    border-radius: 10px;\n"
"}")
        self.status_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_bg.setObjectName("status_bg")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(455, 15, 540, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 55))
        self.label_2.setMaximumSize(QtCore.QSize(540, 60))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 24pt \"STZhongsong\";\n"
"padding: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.status_bar = QtWidgets.QFrame(self.centralwidget)
        self.status_bar.setGeometry(QtCore.QRect(1259, 90, 641, 60))
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.status_bar)
        self.horizontalLayout_6.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.status = QtWidgets.QFrame(self.status_bar)
        self.status.setMaximumSize(QtCore.QSize(120, 16777215))
        self.status.setObjectName("status")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.status)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lights = QtWidgets.QLabel(self.status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lights.sizePolicy().hasHeightForWidth())
        self.lights.setSizePolicy(sizePolicy)
        self.lights.setMinimumSize(QtCore.QSize(30, 30))
        self.lights.setMaximumSize(QtCore.QSize(30, 30))
        self.lights.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 15px;\n"
"")
        self.lights.setText("")
        self.lights.setObjectName("lights")
        self.horizontalLayout_3.addWidget(self.lights)
        self.caption = QtWidgets.QLabel(self.status)
        self.caption.setMinimumSize(QtCore.QSize(0, 0))
        self.caption.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.caption.setStyleSheet("QLabel{\n"
"    font: 22pt  \"STZhongsong\";\n"
"    text-decoration: underline;\n"
"    color: white;\n"
"    background-color: rgb(70, 130, 180);\n"
"    margin: 6pt;\n"
"}\n"
"")
        self.caption.setAlignment(QtCore.Qt.AlignCenter)
        self.caption.setObjectName("caption")
        self.horizontalLayout_3.addWidget(self.caption)
        self.horizontalLayout_6.addWidget(self.status)
        self.date_time = QtWidgets.QFrame(self.status_bar)
        self.date_time.setObjectName("date_time")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.date_time)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date = QtWidgets.QLabel(self.date_time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        self.date.setStyleSheet("QLabel{\n"
"    font: 22pt  \"黑体\";\n"
"    color: white;\n"
"    background-color: rgb(70, 130, 180);\n"
"    margin: 6pt;\n"
"}\n"
"")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.time = QtWidgets.QLabel(self.date_time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setStyleSheet("QLabel{\n"
"    font: 22pt  \"黑体\";\n"
"    color: white;\n"
"    background-color: rgb(70, 130, 180);\n"
"    margin: 6pt;\n"
"}\n"
"")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time)
        self.horizontalLayout_6.addWidget(self.date_time)
        self.log_in_out = QtWidgets.QFrame(self.status_bar)
        self.log_in_out.setMaximumSize(QtCore.QSize(140, 40))
        self.log_in_out.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"border-radius: 10px;")
        self.log_in_out.setObjectName("log_in_out")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.log_in_out)
        self.horizontalLayout_7.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.log_in = QtWidgets.QPushButton(self.log_in_out)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_in.sizePolicy().hasHeightForWidth())
        self.log_in.setSizePolicy(sizePolicy)
        self.log_in.setStyleSheet("QPushButton{\n"
"height: 40px;\n"
"width: 80px;\n"
"background:rgb(255, 255, 255);\n"
"font: 22pt \"STZhongsong\" rgb(0, 0, 0);\n"
"border: 2px;\n"
"    border-color: rgb(136, 136, 136);\n"
"}\n"
"QPushButton{border: 2px;}\n"
"QPushButton{border-radius: 10px;}\n"
"\n"
"QPushButton:hover{background:rgb(145, 145, 145);}\n"
"")
        self.log_in.setObjectName("log_in")
        self.horizontalLayout_7.addWidget(self.log_in)
        self.quit = QtWidgets.QPushButton(self.log_in_out)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit.sizePolicy().hasHeightForWidth())
        self.quit.setSizePolicy(sizePolicy)
        self.quit.setStyleSheet("QPushButton{\n"
"height: 40px;\n"
"width: 80px;\n"
"background:rgb(136, 136, 136);\n"
"font: 22pt \"STZhongsong\" rgb(0, 0, 0);\n"
"}\n"
"QPushButton{border: 2px;}\n"
"QPushButton{border-radius: 10px;}\n"
"\n"
"QPushButton:hover{background:rgb(145, 145, 145);}\n"
"")
        self.quit.setObjectName("quit")
        self.horizontalLayout_7.addWidget(self.quit)
        self.horizontalLayout_6.addWidget(self.log_in_out)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1565, 1010, 350, 30))
        self.label_9.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.control = QtWidgets.QFrame(self.centralwidget)
        self.control.setGeometry(QtCore.QRect(1560, 180, 345, 821))
        self.control.setObjectName("control")
        self.groupBox_11 = QtWidgets.QGroupBox(self.control)
        self.groupBox_11.setGeometry(QtCore.QRect(1, 10, 350, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setStyleSheet("font: 28pt \"STZhongsong\";")
        self.groupBox_11.setObjectName("groupBox_11")
        self.frame_23 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_23.setGeometry(QtCore.QRect(0, 40, 355, 251))
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(20)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.count_stop = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.count_stop.sizePolicy().hasHeightForWidth())
        self.count_stop.setSizePolicy(sizePolicy)
        self.count_stop.setMinimumSize(QtCore.QSize(300, 75))
        self.count_stop.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_stop.setFont(font)
        self.count_stop.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.count_stop.setObjectName("count_stop")
        self.gridLayout_6.addWidget(self.count_stop, 1, 0, 1, 1)
        self.count_begin = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.count_begin.sizePolicy().hasHeightForWidth())
        self.count_begin.setSizePolicy(sizePolicy)
        self.count_begin.setMinimumSize(QtCore.QSize(300, 75))
        self.count_begin.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_begin.setFont(font)
        self.count_begin.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.count_begin.setObjectName("count_begin")
        self.gridLayout_6.addWidget(self.count_begin, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.control)
        self.groupBox_12.setGeometry(QtCore.QRect(1, 340, 350, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setStyleSheet("font: 28pt \"STZhongsong\";")
        self.groupBox_12.setObjectName("groupBox_12")
        self.frame_22 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_22.setGeometry(QtCore.QRect(0, 30, 355, 441))
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.file_save = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.file_save.sizePolicy().hasHeightForWidth())
        self.file_save.setSizePolicy(sizePolicy)
        self.file_save.setMinimumSize(QtCore.QSize(300, 75))
        self.file_save.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.file_save.setFont(font)
        self.file_save.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.file_save.setObjectName("file_save")
        self.gridLayout_5.addWidget(self.file_save, 3, 0, 1, 1)
        self.video_browser = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.video_browser.sizePolicy().hasHeightForWidth())
        self.video_browser.setSizePolicy(sizePolicy)
        self.video_browser.setMinimumSize(QtCore.QSize(300, 75))
        self.video_browser.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_browser.setFont(font)
        self.video_browser.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.video_browser.setObjectName("video_browser")
        self.gridLayout_5.addWidget(self.video_browser, 1, 0, 1, 1)
        self.table_save = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.table_save.sizePolicy().hasHeightForWidth())
        self.table_save.setSizePolicy(sizePolicy)
        self.table_save.setMinimumSize(QtCore.QSize(300, 75))
        self.table_save.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.table_save.setFont(font)
        self.table_save.setStyleSheet("QPushButton{\n"
"    font-family: \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.table_save.setObjectName("table_save")
        self.gridLayout_5.addWidget(self.table_save, 2, 0, 1, 1)
        self.camera_open = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.camera_open.sizePolicy().hasHeightForWidth())
        self.camera_open.setSizePolicy(sizePolicy)
        self.camera_open.setMinimumSize(QtCore.QSize(300, 75))
        self.camera_open.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.camera_open.setFont(font)
        self.camera_open.setStyleSheet("QPushButton{\n"
"    font-family:  \"STZhongsong\";\n"
"    font-size: 26pt;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(99, 145, 182);\n"
"    border-color: rgb(99, 145, 182);\n"
"    border-radius: 10px;\n"
"    border: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(70, 130, 180);}\n"
"\n"
"\n"
"QPushButton:pressed{background:rgb(45, 113, 180);}\n"
"")
        self.camera_open.setObjectName("camera_open")
        self.gridLayout_5.addWidget(self.camera_open, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 15, 191, 61))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(215, 15, 151, 51))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(365, 15, 81, 71))
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_9.raise_()
        self.label_2.raise_()
        self.status_bg.raise_()
        self.tabWidget.raise_()
        self.status_bar.raise_()
        self.control.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.media_display.setText(_translate("MainWindow", "实时监视窗口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monitor), _translate("MainWindow", "监视窗口"))
        self.build_display.setText(_translate("MainWindow", "显示窗口"))
        self.build_begin.setText(_translate("MainWindow", "开始建模"))
        self.build_stop.setText(_translate("MainWindow", "停止建模"))
        self.label_21.setText(_translate("MainWindow", "使用说明"))
        self.manual_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">本软件提供智能轨道建模功能。用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「开始建模」</span><span style=\" font-size:18pt;\">按钮对空轨道就行建模，</span><span style=\" font-family:\'等线\'; font-size:18pt; color:#000000;\">并可视化轨道的RGB信息和深度信息。</span><span style=\" font-size:18pt;\">按下</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「停止建模」</span><span style=\" font-size:18pt;\">按钮则完成建模，同时在窗口右侧显示轨道截面的拟合曲线图。</span></p></body></html>"))
        self.build_result.setText(_translate("MainWindow", "显示窗口"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "轨道建模"))
        item = self.num_dis.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "开始时间"))
        item = self.num_dis.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "结束时间"))
        item = self.num_dis.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "鱼类数量"))
        self.label_19.setText(_translate("MainWindow", "使用说明"))
        self.manual_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">本软件提供高精度鱼类计数功能。用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「开始计数」</span><span style=\" font-size:18pt;\">按钮进入鱼群计数状态,并同时记录开始时间于该表格。按下</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「停止计数」</span><span style=\" font-size:18pt;\">按钮则停止计数，同时记录结束时间并将期间检测到的鱼类数量记录于该表格中。用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「计数保存」</span><span style=\" font-size:18pt;\">按钮导出包含开始、结束时间和鱼类数量的汇总表格。</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "鱼群数据"))
        self.label_18.setText(_translate("MainWindow", "视频保存格式"))
        self.video_format_mp4.setText(_translate("MainWindow", ".mp4"))
        self.video_format_mkv.setText(_translate("MainWindow", ".mkv"))
        self.video_format_avi.setText(_translate("MainWindow", ".avi"))
        self.label_5.setText(_translate("MainWindow", "内存占用"))
        self.label_32.setText(_translate("MainWindow", "表格保存路径"))
        self.label_6.setText(_translate("MainWindow", "CPU 占用"))
        self.curr_table_dir.setText(_translate("MainWindow", "./data/count"))
        self.change_table_dir.setText(_translate("MainWindow", "更改"))
        self.cpu_tempeture_label.setText(_translate("MainWindow", "xx ℃"))
        self.curr_video_dir.setText(_translate("MainWindow", "TextLabel"))
        self.change_video_dir.setText(_translate("MainWindow", "更改"))
        self.ram_usage_label.setText(_translate("MainWindow", "xx/xx"))
        self.label_16.setText(_translate("MainWindow", "鱼群计数"))
        self.label_7.setText(_translate("MainWindow", "CPU 温度"))
        self.label_13.setText(_translate("MainWindow", "视频保存路径"))
        self.cpu_usage_label.setText(_translate("MainWindow", "xx/xx"))
        self.det_state_on.setText(_translate("MainWindow", "开启"))
        self.det_state_off.setText(_translate("MainWindow", "关闭"))
        self.label_8.setText(_translate("MainWindow", "系统状态"))
        self.label_17.setText(_translate("MainWindow", "使用说明"))
        self.manual_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">1. 鱼群计数</span></p><p><span style=\" font-size:18pt;\">本软件提供高精度鱼类计数功能。用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「开始计数」</span><span style=\" font-size:18pt;\">按钮进入鱼群计数状态，按下</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「停止计数」</span><span style=\" font-size:18pt;\">按钮则停止计数。鱼群计数状态将保存检测的鱼群总数和鱼类个体的外观长宽数据，并将实时图像进行录制保存。</span></p><p><span style=\" font-size:18pt;\">2. 视频回放</span></p><p><span style=\" font-size:18pt;\">在使用过程中，录制视频的保存路径为当前软件目录下 \'media\' 文件夹中的 \'video\' 文件夹，用户可在</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「系统设置」</span><span style=\" font-size:18pt;\">页面修改视频保存路径。此外，用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「视频回放」</span><span style=\" font-size:18pt;\">按钮查看已保存的视频。</span></p><p><span style=\" font-size:18pt;\">3. 计数保存</span></p><p><span style=\" font-size:18pt;\">在使用过程中，鱼群数据表格将统计鱼群总数和鱼类个体的外观长宽数据，其默认保存路径为当前软件目录下 \'data\' 文件夹中的 \'count\'文件夹，用户也可在</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「系统设置」</span><span style=\" font-size:18pt;\">页面修改表格保存路径。此外，用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「表格查看」</span><span style=\" font-size:18pt;\">按钮查看已保存的表格。</span></p><p><span style=\" font-size:18pt;\">4. 文件保存</span></p><p><span style=\" font-size:18pt;\">用户可通过点击</span><span style=\" font-family:\'等线\'; font-size:18pt; font-weight:600; color:#000000;\">「文件保存」</span><span style=\" font-size:18pt;\">按钮拷贝或转存所需数据表格及录制视频文件。<br/></span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.system_cfg), _translate("MainWindow", "系统设置"))
        self.label_2.setText(_translate("MainWindow", "高清全彩边缘智能视觉鱼群监测系统"))
        self.caption.setText(_translate("MainWindow", "正常"))
        self.date.setText(_translate("MainWindow", "20XX-XX-XX"))
        self.time.setText(_translate("MainWindow", "13:50:59"))
        self.log_in.setText(_translate("MainWindow", "运行"))
        self.quit.setText(_translate("MainWindow", "退出"))
        self.label_9.setText(_translate("MainWindow", "Copyright 2023 - 2024 © V4R  v1.0"))
        self.groupBox_11.setTitle(_translate("MainWindow", "鱼群计数"))
        self.count_stop.setText(_translate("MainWindow", "结束计数"))
        self.count_begin.setText(_translate("MainWindow", "开始计数"))
        self.groupBox_12.setTitle(_translate("MainWindow", "控制面板"))
        self.file_save.setText(_translate("MainWindow", "数据保存"))
        self.video_browser.setText(_translate("MainWindow", "视频回看"))
        self.table_save.setText(_translate("MainWindow", "数据查看"))
        self.camera_open.setText(_translate("MainWindow", "打开相机"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/src/fish_txt_logo.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/src/tj_txt_logo2.png\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/chunyu_logo5.png\"/></p></body></html>"))
import picture_rc
